import sanitizeHtml from "sanitize-html";

const ALLOWED_TAGS = [
  "section",
  "header",
  "footer",
  "main",
  "article",
  "aside",
  "nav",
  "div",
  "span",
  "p",
  "a",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "dl",
  "dt",
  "dd",
  "blockquote",
  "cite",
  "figure",
  "figcaption",
  "picture",
  "source",
  "img",
  "video",
  "svg",
  "path",
  "circle",
  "rect",
  "g",
  "line",
  "polyline",
  "polygon",
  "defs",
  "linearGradient",
  "radialGradient",
  "stop",
  "button",
  "strong",
  "em",
  "small",
  "code",
  "br",
  "hr",
  "label",
  "input",
  "style",
];

const ALLOWED_ATTRS_ALL = [
  "class",
  "style",
  "id",
  "role",
  "aria-label",
  "aria-hidden",
  "aria-labelledby",
  "data-*",
];

export function sanitizeBlockHtml(input: string): string {
  return sanitizeHtml(input, {
    allowedTags: ALLOWED_TAGS,
    allowedAttributes: {
      "*": ALLOWED_ATTRS_ALL,
      a: ["href", "target", "rel", ...ALLOWED_ATTRS_ALL],
      img: ["src", "alt", "width", "height", "loading", ...ALLOWED_ATTRS_ALL],
      video: [
        "src",
        "poster",
        "controls",
        "autoplay",
        "loop",
        "muted",
        "playsinline",
        ...ALLOWED_ATTRS_ALL,
      ],
      source: ["src", "type", "srcset", "media", ...ALLOWED_ATTRS_ALL],
      svg: [
        "viewBox",
        "width",
        "height",
        "fill",
        "stroke",
        "xmlns",
        ...ALLOWED_ATTRS_ALL,
      ],
      path: [
        "d",
        "fill",
        "stroke",
        "stroke-width",
        "stroke-linecap",
        "stroke-linejoin",
        ...ALLOWED_ATTRS_ALL,
      ],
      circle: ["cx", "cy", "r", "fill", "stroke", ...ALLOWED_ATTRS_ALL],
      rect: [
        "x",
        "y",
        "width",
        "height",
        "rx",
        "ry",
        "fill",
        "stroke",
        ...ALLOWED_ATTRS_ALL,
      ],
      line: ["x1", "y1", "x2", "y2", "stroke", ...ALLOWED_ATTRS_ALL],
      polyline: ["points", "fill", "stroke", ...ALLOWED_ATTRS_ALL],
      polygon: ["points", "fill", "stroke", ...ALLOWED_ATTRS_ALL],
      g: ["transform", "fill", "stroke", ...ALLOWED_ATTRS_ALL],
      stop: ["offset", "stop-color", "stop-opacity", ...ALLOWED_ATTRS_ALL],
      linearGradient: [
        "x1",
        "y1",
        "x2",
        "y2",
        "gradientUnits",
        ...ALLOWED_ATTRS_ALL,
      ],
      radialGradient: [
        "cx",
        "cy",
        "r",
        "gradientUnits",
        ...ALLOWED_ATTRS_ALL,
      ],
      input: [
        "type",
        "name",
        "placeholder",
        "required",
        "value",
        ...ALLOWED_ATTRS_ALL,
      ],
      button: ["type", ...ALLOWED_ATTRS_ALL],
      style: ALLOWED_ATTRS_ALL,
    },
    allowedSchemes: ["http", "https", "mailto", "data"],
    allowedSchemesByTag: { img: ["http", "https", "data"] },
    // Permit inline <style> contents to pass through unchanged.
    allowVulnerableTags: true,
    parseStyleAttributes: false,
  });
}
